2024-03-23 17:26:38.475 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.477 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.478 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.480 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.482 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration favicon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.485 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.487 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration qr_generator which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.489 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.490 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration npm_switches which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.492 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:38.493 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-23 17:26:53.658 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/browser_mod/mod_view.py, line 24: hass.components.frontend.async_register_built_in_panel(, please report it to the author of the 'browser_mod' custom integration
2024-03-23 17:26:54.694 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.tapo_control.light.TapoWhitelight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues
2024-03-23 17:26:55.180 WARNING (MainThread) [homeassistant.setup] Setup of rest is taking over 10 seconds.
2024-03-23 18:19:39.910 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: Timeout occurred while connecting to WLED device at 10.20.10.14
2024-03-23 18:20:47.868 ERROR (Thread-101) [pychromecast.socket_client] [Bedroom TV(10.20.10.9):8009] Failed to connect to service MDNSServiceInfo(name='Chromecast-45ff6b65913dc076315ce64817332d51._googlecast._tcp.local.'), retrying in 5.0s
2024-03-23 18:20:47.935 ERROR (Thread-102) [pychromecast.socket_client] [AllSpeaker(10.20.10.9):32082] Failed to connect to service MDNSServiceInfo(name='Google-Cast-Group-6E215B7CE162467AAC6A69A8114D1808._googlecast._tcp.local.'), retrying in 5.0s
2024-03-23 18:23:40.579 WARNING (Thread-102) [pychromecast.socket_client] [AllSpeaker(10.20.10.9):32082] Heartbeat timeout, resetting connection
2024-03-23 18:23:40.587 WARNING (Thread-101) [pychromecast.socket_client] [Bedroom TV(10.20.10.9):8009] Heartbeat timeout, resetting connection
2024-03-23 18:24:10.617 ERROR (Thread-101) [pychromecast.socket_client] [Bedroom TV(10.20.10.9):8009] Failed to connect to service MDNSServiceInfo(name='Chromecast-45ff6b65913dc076315ce64817332d51._googlecast._tcp.local.'), retrying in 5.0s
2024-03-23 18:24:10.620 ERROR (Thread-102) [pychromecast.socket_client] [AllSpeaker(10.20.10.9):32082] Failed to connect to service MDNSServiceInfo(name='Google-Cast-Group-6E215B7CE162467AAC6A69A8114D1808._googlecast._tcp.local.'), retrying in 5.0s
2024-03-23 18:39:02.087 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.myip is taking over 10 seconds
2024-03-23 18:49:02.091 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.myip is taking over 10 seconds
2024-03-23 19:05:02.100 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.myip is taking over 10 seconds
2024-03-23 19:37:19.665 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: Timeout occurred while connecting to WLED device at 10.20.10.14
2024-03-23 19:45:02.116 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.myip is taking over 10 seconds
2024-03-23 19:58:58.987 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: (503, {'error': 3})
2024-03-23 20:11:47.630 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: (503, {'error': 3})
2024-03-23 20:39:35.890 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: (503, {'error': 3})
2024-03-23 20:49:15.756 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: Timeout occurred while connecting to WLED device at 10.20.10.14
2024-03-23 20:51:49.458 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: Timeout occurred while connecting to WLED device at 10.20.10.14
2024-03-23 21:09:42.683 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.pujaphone_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2024-03-23 21:09:52.610 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.pujaphone_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2024-03-23 21:11:02.156 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.myip is taking over 10 seconds
2024-03-23 21:12:15.713 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.pujaphone_active_notification_count exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2024-03-23 21:33:36.856 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 404
2024-03-23 21:33:36.858 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546878587456] Unable to sync devices with result code: 404, check log for more info.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 139, in _async_press_action
    await self.async_press()
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/button.py", line 59, in async_press
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Unable to sync devices with result code: 404, check log for more info.
2024-03-23 21:41:01.122 ERROR (Thread-102) [pychromecast.socket_client] [AllSpeaker(10.20.10.9):32082] Failed to connect. No retries.
2024-03-23 21:41:01.123 ERROR (Thread-101) [pychromecast.socket_client] [Bedroom TV(10.20.10.9):8009] Failed to connect. No retries.
